import type { CollectionConfig } from 'payload'

export const CONFLICT_TYPES = [
  { label: 'Airstrike', value: 'airstrike' },
  { label: 'Artillery / Shelling', value: 'artillery_shelling' },
  { label: 'Ground Combat', value: 'ground_combat' },
  { label: 'Naval Strike', value: 'naval_strike' },
  { label: 'Drone Strike', value: 'drone_strike' },
  { label: 'Missile Strike', value: 'missile_strike' },
  { label: 'Roadside Bomb (IED)', value: 'roadside_bomb' },
  { label: 'VBIED (Car Bomb)', value: 'vbied' },
  { label: 'Suicide Bombing', value: 'suicide_bombing' },
  { label: 'Landmine', value: 'landmine' },
  { label: 'Assassination', value: 'assassination' },
  { label: 'Coup Attempt', value: 'coup_attempt' },
  { label: 'Massacre', value: 'massacre' },
  { label: 'Ethnic Violence', value: 'ethnic_violence' },
  { label: 'Protest', value: 'protest' },
  { label: 'Riot', value: 'riot' },
  { label: 'Civil Unrest', value: 'civil_unrest' },
  { label: 'Strike Action', value: 'strike_action' },
  { label: 'Civilian Casualties', value: 'civilian_casualties' },
  { label: 'Mass Displacement', value: 'mass_displacement' },
  { label: 'Aid Blockade', value: 'aid_blockade' },
  { label: 'Famine', value: 'famine' },
  { label: 'Bridge / Road Destroyed', value: 'infrastructure_bridge_road' },
  { label: 'Power Grid Strike', value: 'infrastructure_power' },
  { label: 'Hospital Attack', value: 'infrastructure_hospital' },
  { label: 'Port Blockade', value: 'infrastructure_port' },
  { label: 'Other', value: 'other' },
]

export const Events: CollectionConfig = {
  slug: 'events',
  admin: {
    useAsTitle: 'title',
    defaultColumns: [
      'title',
      'status',
      'conflict_type',
      'severity',
      'confidence_score',
      'country',
      'event_date',
      'createdAt',
    ],
    group: 'Content',
    description: 'Conflict events extracted from Reddit by the AI agent',
    pagination: { defaultLimit: 25 },
  },
  versions: {
    drafts: false,
    maxPerDoc: 10,
  },
  access: {
    read: ({ req: { user } }) => {
      if (user) return true
      return { status: { equals: 'published' } }
    },
    create: ({ req: { user } }) =>
      user?.role === 'super_admin' || user?.role === 'moderator',
    update: ({ req: { user } }) =>
      user?.role === 'super_admin' || user?.role === 'moderator',
    delete: ({ req: { user } }) => user?.role === 'super_admin',
  },
  fields: [
    // ── Core ──────────────────────────────────────────────────
    {
      name: 'title',
      type: 'text',
      required: true,
      admin: { description: 'Short descriptive title generated by Claude' },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'review',
      options: [
        { label: '⏳ Pending Review', value: 'review' },
        { label: '✅ Published', value: 'published' },
        { label: '❌ Rejected', value: 'rejected' },
        { label: '🗄️ Archived', value: 'archived' },
      ],
      admin: {
        position: 'sidebar',
        description: 'New events start as "review". Publish to show on the public map.',
      },
    },
    {
      name: 'description',
      type: 'textarea',
      admin: {
        description: '2-3 sentence neutral summary generated by Claude',
        rows: 4,
      },
    },

    // ── Classification ────────────────────────────────────────
    {
      name: 'conflict_type',
      type: 'select',
      required: true,
      options: CONFLICT_TYPES,
    },
    {
      name: 'severity',
      type: 'number',
      required: true,
      min: 1,
      max: 10,
      admin: {
        description: 'Severity 1–10 (10 = mass casualty / major battle)',
        step: 1,
      },
    },
    {
      name: 'parties',
      type: 'array',
      admin: { description: 'Named parties involved' },
      fields: [
        { name: 'name', type: 'text', required: true },
      ],
    },

    // ── Location ──────────────────────────────────────────────
    {
      name: 'location_name',
      type: 'text',
      admin: { description: 'Human-readable location (e.g. "Kharkiv, Ukraine")' },
    },
    {
      name: 'country',
      type: 'text',
      admin: { description: 'ISO 3166-1 alpha-2 country code (e.g. "UA", "SY")' },
    },
    {
      name: 'region',
      type: 'text',
      admin: { description: 'State, province, or region name' },
    },
    {
      name: 'latitude',
      type: 'number',
      admin: { description: 'Decimal latitude (-90 to 90)', step: 0.000001 },
    },
    {
      name: 'longitude',
      type: 'number',
      admin: { description: 'Decimal longitude (-180 to 180)', step: 0.000001 },
    },

    // ── Dates ─────────────────────────────────────────────────
    {
      name: 'event_date',
      type: 'date',
      admin: {
        description: 'Date the event occurred (not the post date)',
        date: { pickerAppearance: 'dayOnly', displayFormat: 'MMM d, yyyy' },
      },
    },

    // ── Confidence & Verification ─────────────────────────────
    {
      name: 'confidence_score',
      type: 'number',
      min: 0,
      max: 1,
      admin: {
        description: 'Location confidence 0.0–1.0. Below 0.5 = treat with caution.',
        step: 0.01,
      },
    },
    {
      name: 'verification_status',
      type: 'select',
      defaultValue: 'unverified',
      options: [
        { label: 'Unverified', value: 'unverified' },
        { label: 'Community Verified', value: 'community_verified' },
        { label: 'Cross-Source Confirmed', value: 'cross_source_confirmed' },
      ],
      admin: { position: 'sidebar' },
    },

    // ── Media Flags ───────────────────────────────────────────
    {
      name: 'has_footage',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Source post contains or links to footage' },
    },
    {
      name: 'is_graphic',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Footage contains graphic/violent content — triggers content warning' },
    },

    // ── AI Metadata ───────────────────────────────────────────
    {
      name: 'ai_extraction_notes',
      type: 'textarea',
      admin: {
        description: 'Caveats or flags from Claude for the human moderator',
        rows: 3,
      },
    },
    {
      name: 'moderator_notes',
      type: 'textarea',
      admin: {
        description: 'Internal moderator notes (not shown publicly)',
        rows: 3,
      },
    },

    // ── Relationships ─────────────────────────────────────────
    {
      name: 'sources',
      type: 'relationship',
      relationTo: 'sources',
      hasMany: true,
    },
    {
      name: 'media_attachments',
      type: 'relationship',
      relationTo: 'media-attachments',
      hasMany: true,
    },
    {
      name: 'agent_run',
      type: 'relationship',
      relationTo: 'agent-runs',
      hasMany: false,
      admin: { position: 'sidebar' },
    },
  ],
  timestamps: true,
}
