/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    sources: Source;
    'media-attachments': MediaAttachment;
    'agent-runs': AgentRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'media-attachments': MediaAttachmentsSelect<false> | MediaAttachmentsSelect<true>;
    'agent-runs': AgentRunsSelect<false> | AgentRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * super_admin: full access | moderator: review/publish events | api_user: read-only
   */
  role: 'super_admin' | 'moderator' | 'api_user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Conflict events extracted from Reddit by the AI agent
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Short descriptive title generated by Claude
   */
  title: string;
  /**
   * New events start as "review". Publish to show on the public map.
   */
  status: 'review' | 'published' | 'rejected' | 'archived';
  /**
   * 2-3 sentence neutral summary generated by Claude
   */
  description?: string | null;
  conflict_type:
    | 'airstrike'
    | 'artillery_shelling'
    | 'ground_combat'
    | 'naval_strike'
    | 'drone_strike'
    | 'missile_strike'
    | 'roadside_bomb'
    | 'vbied'
    | 'suicide_bombing'
    | 'landmine'
    | 'assassination'
    | 'coup_attempt'
    | 'massacre'
    | 'ethnic_violence'
    | 'protest'
    | 'riot'
    | 'civil_unrest'
    | 'strike_action'
    | 'civilian_casualties'
    | 'mass_displacement'
    | 'aid_blockade'
    | 'famine'
    | 'infrastructure_bridge_road'
    | 'infrastructure_power'
    | 'infrastructure_hospital'
    | 'infrastructure_port'
    | 'other';
  /**
   * Severity 1–10 (10 = mass casualty / major battle)
   */
  severity: number;
  /**
   * Named parties involved
   */
  parties?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Human-readable location (e.g. "Kharkiv, Ukraine")
   */
  location_name?: string | null;
  /**
   * ISO 3166-1 alpha-2 country code (e.g. "UA", "SY")
   */
  country?: string | null;
  /**
   * State, province, or region name
   */
  region?: string | null;
  /**
   * Decimal latitude (-90 to 90)
   */
  latitude?: number | null;
  /**
   * Decimal longitude (-180 to 180)
   */
  longitude?: number | null;
  /**
   * Date the event occurred (not the post date)
   */
  event_date?: string | null;
  /**
   * Location confidence 0.0–1.0. Below 0.5 = treat with caution.
   */
  confidence_score?: number | null;
  verification_status?: ('unverified' | 'community_verified' | 'cross_source_confirmed') | null;
  /**
   * Source post contains or links to footage
   */
  has_footage?: boolean | null;
  /**
   * Footage contains graphic/violent content — triggers content warning
   */
  is_graphic?: boolean | null;
  /**
   * Caveats or flags from Claude for the human moderator
   */
  ai_extraction_notes?: string | null;
  /**
   * Internal moderator notes (not shown publicly)
   */
  moderator_notes?: string | null;
  sources?: (number | Source)[] | null;
  media_attachments?: (number | MediaAttachment)[] | null;
  agent_run?: (number | null) | AgentRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reddit posts and other sources linked to conflict events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  platform: 'reddit' | 'twitter' | 'telegram' | 'news_wire' | 'other';
  /**
   * Unique post ID from the platform (e.g. Reddit post ID "1abc23")
   */
  post_id: string;
  /**
   * Full URL to the original post
   */
  post_url: string;
  /**
   * Subreddit name without r/ prefix (e.g. "CombatFootage")
   */
  subreddit?: string | null;
  /**
   * Original post title from Reddit
   */
  post_title?: string | null;
  /**
   * Post body text — stored for audit trail
   */
  post_body?: string | null;
  /**
   * When the post was published on Reddit
   */
  posted_at?: string | null;
  /**
   * Upvote count at time of ingestion
   */
  upvotes?: number | null;
  /**
   * Upvote ratio 0.0–1.0
   */
  upvote_ratio?: number | null;
  /**
   * Post flair tag from Reddit (e.g. "Breaking", "Geolocated")
   */
  flair?: string | null;
  /**
   * Exact text sent to Claude — stored for debugging and audit trail
   */
  raw_extraction_input?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Media links associated with conflict events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-attachments".
 */
export interface MediaAttachment {
  id: number;
  media_type: 'article_link' | 'image_link' | 'video_link';
  /**
   * Full URL to the external media
   */
  url: string;
  /**
   * URL to a thumbnail/preview image
   */
  thumbnail_url?: string | null;
  platform?: ('reddit' | 'youtube' | 'twitter' | 'telegram' | 'news_site' | 'other') | null;
  /**
   * Optional title or caption
   */
  title?: string | null;
  /**
   * Triggers content warning gate on the frontend
   */
  is_graphic?: boolean | null;
  /**
   * Specific warning text (e.g. "Graphic: combat footage, casualties")
   */
  content_warning?: string | null;
  /**
   * Manually verified as authentic by a moderator
   */
  verified_authentic?: boolean | null;
  /**
   * How authenticity was verified
   */
  verification_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI agent pipeline execution logs — monitor agent health here
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs".
 */
export interface AgentRun {
  id: number;
  /**
   * When this agent run started
   */
  run_at: string;
  status: 'running' | 'completed' | 'failed' | 'completed_with_errors';
  /**
   * Subreddits polled in this run
   */
  subreddits_checked?:
    | {
        name: string;
        posts_fetched?: number | null;
        posts_passed_filter?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Posts sent to Claude
   */
  posts_processed?: number | null;
  /**
   * New events added
   */
  events_created?: number | null;
  /**
   * Existing events updated
   */
  events_updated?: number | null;
  /**
   * Posts identified as duplicates
   */
  events_deduplicated?: number | null;
  /**
   * Posts already processed previously
   */
  posts_skipped?: number | null;
  /**
   * Total run duration in milliseconds
   */
  duration_ms?: number | null;
  claude_api_calls?: number | null;
  geocoding_calls?: number | null;
  /**
   * Errors encountered during this run
   */
  errors?:
    | {
        stage?:
          | ('reddit_fetch' | 'claude_extraction' | 'geocoding' | 'deduplication' | 'database_write' | 'other')
          | null;
        message: string;
        post_id?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'media-attachments';
        value: number | MediaAttachment;
      } | null)
    | ({
        relationTo: 'agent-runs';
        value: number | AgentRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  description?: T;
  conflict_type?: T;
  severity?: T;
  parties?:
    | T
    | {
        name?: T;
        id?: T;
      };
  location_name?: T;
  country?: T;
  region?: T;
  latitude?: T;
  longitude?: T;
  event_date?: T;
  confidence_score?: T;
  verification_status?: T;
  has_footage?: T;
  is_graphic?: T;
  ai_extraction_notes?: T;
  moderator_notes?: T;
  sources?: T;
  media_attachments?: T;
  agent_run?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  platform?: T;
  post_id?: T;
  post_url?: T;
  subreddit?: T;
  post_title?: T;
  post_body?: T;
  posted_at?: T;
  upvotes?: T;
  upvote_ratio?: T;
  flair?: T;
  raw_extraction_input?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-attachments_select".
 */
export interface MediaAttachmentsSelect<T extends boolean = true> {
  media_type?: T;
  url?: T;
  thumbnail_url?: T;
  platform?: T;
  title?: T;
  is_graphic?: T;
  content_warning?: T;
  verified_authentic?: T;
  verification_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs_select".
 */
export interface AgentRunsSelect<T extends boolean = true> {
  run_at?: T;
  status?: T;
  subreddits_checked?:
    | T
    | {
        name?: T;
        posts_fetched?: T;
        posts_passed_filter?: T;
        id?: T;
      };
  posts_processed?: T;
  events_created?: T;
  events_updated?: T;
  events_deduplicated?: T;
  posts_skipped?: T;
  duration_ms?: T;
  claude_api_calls?: T;
  geocoding_calls?: T;
  errors?:
    | T
    | {
        stage?: T;
        message?: T;
        post_id?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}